/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2024-09-06-c1a96d33b"
#endif /* AVUTIL_FFVERSION_H */
